name = "day03"
version = "0.1.0"
license = "license"
author = "Nixon Enraght-Moony"
maintainer = "nixon.emoony@gmail.com"
copyright = "Copyright 2022, Nixon Enraght-Moony"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
[dependencies]
stdlib = { git="https://github.com/fortran-lang/stdlib", rev="f27f635f27aee3da45e4c67e46acf4b6dd7a44ba" }
