name = "day03"
version = "0.1.0"
license = "license"
author = "Nixon Enraght-Moony"
maintainer = "nixon.emoony@gmail.com"
copyright = "Copyright 2022, Nixon Enraght-Moony"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
